name: Auto Create pr
on:
  push:
    branches-ignore: main

jobs:
  updateAuthors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # with:
        #   fetch-depth: 0
      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v4.2.3
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     committer: GitHub <noreply@github.com>
      #     commit-message: update authors
      #     title: Update AUTHORS
      #     signoff: false
      #     body: |
      #       Credit new contributors by updating AUTHORS..
      #       🐱
      #     author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
      #     branch: feat-auto-create-pr
      #     base: develop
      #     labels: |
      #       report
      #       automated pr
      - name: Make changes to pull request
        run: date +%s > report.txt

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          base: develop
          branch: feat-auto-create-pr
          title: "[Example-Kaen] Update report"
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            question
          assignees: PawaOx4th
          milestone: 1
          draft: false
